//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS4Control.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS4Control.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery: *number*%.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged.
        /// </summary>
        internal static string Charged {
            get {
                return ResourceManager.GetString("Charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging: *number*%.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *Mac address* was removed or lost connection.
        /// </summary>
        internal static string ControllerWasRemoved {
            get {
                return ResourceManager.GetString("ControllerWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Could not open DS4 *Mac address* exclusively..
        /// </summary>
        internal static string CouldNotOpenDS4 {
            get {
                return ResourceManager.GetString("CouldNotOpenDS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Controller: .
        /// </summary>
        internal static string FoundController {
            get {
                return ResourceManager.GetString("FoundController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must quit other applications like Steam, Uplay before activating the &apos;Hide DS4 Controller&apos; option.&quot;.
        /// </summary>
        internal static string QuitOtherPrograms {
            get {
                return ResourceManager.GetString("QuitOtherPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for controllers….
        /// </summary>
        internal static string SearchingController {
            get {
                return ResourceManager.GetString("SearchingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped DS4Windows.
        /// </summary>
        internal static string StoppedDS4Windows {
            get {
                return ResourceManager.GetString("StoppedDS4Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping DS4 Controllers.
        /// </summary>
        internal static string StoppingDS4 {
            get {
                return ResourceManager.GetString("StoppingDS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping X360 Controllers.
        /// </summary>
        internal static string StoppingX360 {
            get {
                return ResourceManager.GetString("StoppingX360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad Movement is now Off.
        /// </summary>
        internal static string TouchpadMovementOff {
            get {
                return ResourceManager.GetString("TouchpadMovementOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad Movement is now On.
        /// </summary>
        internal static string TouchpadMovementOn {
            get {
                return ResourceManager.GetString("TouchpadMovementOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Exclusive Mode.
        /// </summary>
        internal static string UsingExclusive {
            get {
                return ResourceManager.GetString("UsingExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *number* is using Profile “*Profile name*&quot;.
        /// </summary>
        internal static string UsingProfile {
            get {
                return ResourceManager.GetString("UsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Shared Mode.
        /// </summary>
        internal static string UsingShared {
            get {
                return ResourceManager.GetString("UsingShared", resourceCulture);
            }
        }
    }
}
