//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS4WinWPF.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS4WinWPF.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accel.
        /// </summary>
        public static string Accel {
            get {
                return ResourceManager.GetString("Accel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Directory.
        /// </summary>
        public static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Programs.
        /// </summary>
        public static string AddPrograms {
            get {
                return ResourceManager.GetString("AddPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Start Menu Programs.
        /// </summary>
        public static string AddStartMenuPrograms {
            get {
                return ResourceManager.GetString("AddStartMenuPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Steam Games.
        /// </summary>
        public static string AddSteamGames {
            get {
                return ResourceManager.GetString("AddSteamGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An anti-deadzone acts as an offset for use with an axis to denote the minimum output value generated after an axis has left its assigned deadzone. This is mainly meant to help with mapping an axis to the assigned deadzone value used for an axis in a video game. For example, the typical assigned deadzone for XInput LS in a video game is around 8000 (25%). With no anti-deadzone assigned, an axis would have to move past the assigned deadzone in DS4Windows along with the game&apos;s assigned axis deadzone..
        /// </summary>
        public static string AntiDeadzoneTooltip {
            get {
                return ResourceManager.GetString("AntiDeadzoneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Profiles.
        /// </summary>
        public static string AutoProfiles {
            get {
                return ResourceManager.GetString("AutoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process path. ^ABC = Match at the beginning of string (^) | ABC$ = Match at the end of string ($) | *ABC =Contains a string (*).
        /// </summary>
        public static string AutoProfPathTip {
            get {
                return ResourceManager.GetString("AutoProfPathTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window title. ^ABC = Match at the beginning of string (^) | ABC$ = Match at the end of string ($) | *ABC =Contains a string (*).
        /// </summary>
        public static string AutoProfTitleTip {
            get {
                return ResourceManager.GetString("AutoProfTitleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for Other Programs.
        /// </summary>
        public static string BrowseOtherPrograms {
            get {
                return ResourceManager.GetString("BrowseOtherPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes take effect on new device connection.
        /// </summary>
        public static string ChangeOnNewDeviceConn {
            get {
                return ResourceManager.GetString("ChangeOnNewDeviceConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Update Now.
        /// </summary>
        public static string CheckUpdateNow {
            get {
                return ResourceManager.GetString("CheckUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates at DS4Windows startup.
        /// </summary>
        public static string CheckUpdateStartup {
            get {
                return ResourceManager.GetString("CheckUpdateStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Minimizes.
        /// </summary>
        public static string CloseMinimizes {
            get {
                return ResourceManager.GetString("CloseMinimizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 1.
        /// </summary>
        public static string Controller1Text {
            get {
                return ResourceManager.GetString("Controller1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 2.
        /// </summary>
        public static string Controller2Text {
            get {
                return ResourceManager.GetString("Controller2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 3.
        /// </summary>
        public static string Controller3Text {
            get {
                return ResourceManager.GetString("Controller3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 4.
        /// </summary>
        public static string Controller4Text {
            get {
                return ResourceManager.GetString("Controller4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 5.
        /// </summary>
        public static string Controller5Text {
            get {
                return ResourceManager.GetString("Controller5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 6.
        /// </summary>
        public static string Controller6Text {
            get {
                return ResourceManager.GetString("Controller6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 7.
        /// </summary>
        public static string Controller7Text {
            get {
                return ResourceManager.GetString("Controller7Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 8.
        /// </summary>
        public static string Controller8Text {
            get {
                return ResourceManager.GetString("Controller8Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers.
        /// </summary>
        public static string Controllers {
            get {
                return ResourceManager.GetString("Controllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data integrity checks failed for wireless device. Closing device..
        /// </summary>
        public static string CRC32Fail {
            get {
                return ResourceManager.GetString("CRC32Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Exe Name.
        /// </summary>
        public static string CustomExeName {
            get {
                return ResourceManager.GetString("CustomExeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some games implement a block that causes DS4 input to be ignored if a game detects either DS4Windows.exe or InputMapper.exe running at the time. A workaround to the block is to rename DS4Windows.exe so the check in the game fails. Specifying a custom exe name here allows DS4Updater to automatically update a custom copy of DS4Windows to the desired file name. Make sure to omit the extension.
        ///
        ///Example: whyme_DS4Windows.
        /// </summary>
        public static string CustomExeNameInfo {
            get {
                return ResourceManager.GetString("CustomExeNameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable virtual controller.
        /// </summary>
        public static string DisableVirtualController {
            get {
                return ResourceManager.GetString("DisableVirtualController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not spawn/associate virtual controllers for connected controllers using this profile (Applies on profile save).
        /// </summary>
        public static string DisableVirtualControllerTip {
            get {
                return ResourceManager.GetString("DisableVirtualControllerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller/Driver Setup.
        /// </summary>
        public static string DriverSetup {
            get {
                return ResourceManager.GetString("DriverSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4 BT Poll Rate.
        /// </summary>
        public static string DS4BTPollRate {
            get {
                return ResourceManager.GetString("DS4BTPollRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature currently disabled in app due to driver issues. Hopefully issues get fixed in a future update..
        /// </summary>
        public static string DS4LightbarPassthruDisabled {
            get {
                return ResourceManager.GetString("DS4LightbarPassthruDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Action.
        /// </summary>
        public static string EditAction {
            get {
                return ResourceManager.GetString("EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulated Controller.
        /// </summary>
        public static string EmulatedController {
            get {
                return ResourceManager.GetString("EmulatedController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Output data to DS4.
        /// </summary>
        public static string EnableOutputDataToDS4 {
            get {
                return ResourceManager.GetString("EnableOutputDataToDS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output lightbar and rumble data periodically to DS4 gamepad. Untick if the gamepad doesn&apos;t support data receiving.
        ///Changes to this option takes effect at the gamepad connection time..
        /// </summary>
        public static string EnableOutputDataToDS4Tip {
            get {
                return ResourceManager.GetString("EnableOutputDataToDS4Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Access.
        /// </summary>
        public static string ExclusiveAccess {
            get {
                return ResourceManager.GetString("ExclusiveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flick Threshold.
        /// </summary>
        public static string FlickThreshold {
            get {
                return ResourceManager.GetString("FlickThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flick Time.
        /// </summary>
        public static string FlickTime {
            get {
                return ResourceManager.GetString("FlickTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET 5 Runtime was not detected on your system. Please download and install .NET 5 Runtime to ensure compatibility with future DS4Windows builds. You will be redirected to the .NET 5 Runtime download page upon closing this window..
        /// </summary>
        public static string FutureNetNotInstalled {
            get {
                return ResourceManager.GetString("FutureNetNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps the controller output to a standard XInput gamepad or DS4 pad. Gyro is mapped to a Mouse-like Joystick..
        /// </summary>
        public static string GamepadGyroCameraDescription {
            get {
                return ResourceManager.GetString("GamepadGyroCameraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad with Mouse-like Joystick.
        /// </summary>
        public static string GamepadGyroCameraName {
            get {
                return ResourceManager.GetString("GamepadGyroCameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps the controller output to a standard gamepad.
        /// </summary>
        public static string GamepadPresetDescription {
            get {
                return ResourceManager.GetString("GamepadPresetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad.
        /// </summary>
        public static string GamepadPresetName {
            get {
                return ResourceManager.GetString("GamepadPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad Test.
        /// </summary>
        public static string GamepadTest {
            get {
                return ResourceManager.GetString("GamepadTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyro.
        /// </summary>
        public static string Gyro {
            get {
                return ResourceManager.GetString("Gyro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Unchecked.
        /// </summary>
        public static string HideUnchecked {
            get {
                return ResourceManager.GetString("HideUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HidGuardian Access.
        /// </summary>
        public static string HidGuardianAccess {
            get {
                return ResourceManager.GetString("HidGuardianAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HidHide.
        /// </summary>
        public static string HidHide {
            get {
                return ResourceManager.GetString("HidHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HidHide Access.
        /// </summary>
        public static string HidHideAccess {
            get {
                return ResourceManager.GetString("HidHideAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HidHide Configuration Client.
        /// </summary>
        public static string HidHideConfigClient {
            get {
                return ResourceManager.GetString("HidHideConfigClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HidNinja.
        /// </summary>
        public static string HidNinja {
            get {
                return ResourceManager.GetString("HidNinja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps the controller output to virtual KB+M controls. Useful for playing FPS games with no gamepad support. Gyro is mapped to a virtual Mouse..
        /// </summary>
        public static string KBMGyroMouseDescription {
            get {
                return ResourceManager.GetString("KBMGyroMouseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB+M Controls with Gyro Mouse.
        /// </summary>
        public static string KBMGyroMouseName {
            get {
                return ResourceManager.GetString("KBMGyroMouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps the controller output to virtual KB+M controls. Useful for playing FPS games with no gamepad support..
        /// </summary>
        public static string KBMPresetDescription {
            get {
                return ResourceManager.GetString("KBMPresetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB+M Controls.
        /// </summary>
        public static string KBMPresetName {
            get {
                return ResourceManager.GetString("KBMPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Stick.
        /// </summary>
        public static string LeftStick {
            get {
                return ResourceManager.GetString("LeftStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Angle Threshold.
        /// </summary>
        public static string MinAngleThreshold {
            get {
                return ResourceManager.GetString("MinAngleThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps the buttons and axes to a standard gamepad. Maps the Gyro to a virtual mouse.
        /// </summary>
        public static string MixedGyroMousePresetDescription {
            get {
                return ResourceManager.GetString("MixedGyroMousePresetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad with Gyro Mouse.
        /// </summary>
        public static string MixedGyroMousePresetName {
            get {
                return ResourceManager.GetString("MixedGyroMousePresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps the controller output to mixed XInput gamepad + RS mouse..
        /// </summary>
        public static string MixedPresetDescription {
            get {
                return ResourceManager.GetString("MixedPresetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad with High Precision Camera.
        /// </summary>
        public static string MixedPresetName {
            get {
                return ResourceManager.GetString("MixedPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Action.
        /// </summary>
        public static string NewAction {
            get {
                return ResourceManager.GetString("NewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        public static string NewProfile {
            get {
                return ResourceManager.GetString("NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Controllers Connected (Max {0}).
        /// </summary>
        public static string NoControllersConnected {
            get {
                return ResourceManager.GetString("NoControllersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the type of output virtual controller (Applies on profile save).
        /// </summary>
        public static string OutContNotice {
            get {
                return ResourceManager.GetString("OutContNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use a preset option? Choosing No will cause the Profile Editor to use an empty Gamepad profile..
        /// </summary>
        public static string PresetIntroText {
            get {
                return ResourceManager.GetString("PresetIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Folder.
        /// </summary>
        public static string ProfileFolder {
            get {
                return ResourceManager.GetString("ProfileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Charge.
        /// </summary>
        public static string QuickCharge {
            get {
                return ResourceManager.GetString("QuickCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real World Calibration.
        /// </summary>
        public static string RealWorldCalibration {
            get {
                return ResourceManager.GetString("RealWorldCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string RecordText {
            get {
                return ResourceManager.GetString("RecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Action.
        /// </summary>
        public static string RemoveAction {
            get {
                return ResourceManager.GetString("RemoveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RenameProfile {
            get {
                return ResourceManager.GetString("RenameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Stick.
        /// </summary>
        public static string RightStick {
            get {
                return ResourceManager.GetString("RightStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumble.
        /// </summary>
        public static string Rumble {
            get {
                return ResourceManager.GetString("Rumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string RumbleMaxSecs {
            get {
                return ResourceManager.GetString("RumbleMaxSecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto stop rumble in secs (0=auto stop disabled).
        /// </summary>
        public static string RumbleMaxSecsTip {
            get {
                return ResourceManager.GetString("RumbleMaxSecsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run At Startup.
        /// </summary>
        public static string RunAtStartup {
            get {
                return ResourceManager.GetString("RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuzz specifies the minimum number of device units, in active zone, that the Accel has to be rotated before the output is registered as changed in the mapper. The value is expressed in raw Accel units..
        /// </summary>
        public static string SASteeringWheelFuzzTooltip {
            get {
                return ResourceManager.GetString("SASteeringWheelFuzzTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveProfile {
            get {
                return ResourceManager.GetString("SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Access.
        /// </summary>
        public static string SharedAccess {
            get {
                return ResourceManager.GetString("SharedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notifications.
        /// </summary>
        public static string ShowNotifications {
            get {
                return ResourceManager.GetString("ShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        public static string StartMinimized {
            get {
                return ResourceManager.GetString("StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuzz specifies the minimum number of units the analog stick moves, in active zone, before the output is registered as changed in the mapper. This setting can be useful for worn sticks that cannot maintain a constant position. The value is expressed in raw stick units..
        /// </summary>
        public static string StickFuzzTooltip {
            get {
                return ResourceManager.GetString("StickFuzzTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLD OBSOLETE SETTING. Attempt to apply a curve based on raw input coordinates before any dead zone info is applied. Wonky.
        /// </summary>
        public static string StickInputCurveTooltip {
            get {
                return ResourceManager.GetString("StickInputCurveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always enforce max output setting. Useful for 100% Max Output and confining value to a circular output value.
        /// </summary>
        public static string StickMaxOutputForceTooltip {
            get {
                return ResourceManager.GetString("StickMaxOutputForceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In some situations, it might be useful to limit the maximum value that is output by the output analog stick. Max Output allows throttling the final output value of the analog stick..
        /// </summary>
        public static string StickMaxOutputTooltip {
            get {
                return ResourceManager.GetString("StickMaxOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for when an action will fire.
        /// </summary>
        public static string StickOuterBindDeadTooltip {
            get {
                return ResourceManager.GetString("StickOuterBindDeadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have outer bind fire before reaching a threshold. Action releases once the threshold has been exceeded.
        /// </summary>
        public static string StickOuterBindInvertTooltip {
            get {
                return ResourceManager.GetString("StickOuterBindInvertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to execute when stick travel reaches past a treshold. Useful for mapping keys for Walk or Sprint actions. Invert casues the action to fire up until the threshold.
        /// </summary>
        public static string StickOuterBindTooltip {
            get {
                return ResourceManager.GetString("StickOuterBindTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rotation setting is meant to help correct the orientation of an analog stick if your thumb is slightly shifted when moving an analog stick. For example, your thumb might be slightly shifted from center when the analog stick is moved fully north. My thumbs shift slightly to the right when moving an analog stick fully north due to the way my hands grip the DS4. The value used denotes the number of degrees used to adjust the final axis output value. Values allows range from -180 to 180. Default is 0..
        /// </summary>
        public static string StickRotationTooltip {
            get {
                return ResourceManager.GetString("StickRotationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle low end of Touchpad movement. Reduces accidental mouse cursor movement when holding a mostly fixed position on the Touchpad.
        /// </summary>
        public static string TouchpadJitterCompTooltip {
            get {
                return ResourceManager.GetString("TouchpadJitterCompTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum calculated output travel before a Mouse event is sent to the system.
        /// </summary>
        public static string TouchpadMinThresholdTooltip {
            get {
                return ResourceManager.GetString("TouchpadMinThresholdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts a touchpad swipe by a given rotation angle. Useful when a normal touchpad swipe is not a straight line across. Values allows range from -180 to 180. Default is 0..
        /// </summary>
        public static string TouchpadRotationTooltip {
            get {
                return ResourceManager.GetString("TouchpadRotationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity used to engage a multi-touch Mouse Wheel Scroll action.
        /// </summary>
        public static string TouchpadSlideTooltip {
            get {
                return ResourceManager.GetString("TouchpadSlideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Mouse Left click with a Touchpad Tap. Max time interval is set at (value * 2) ms..
        /// </summary>
        public static string TouchpadTapTooltip {
            get {
                return ResourceManager.GetString("TouchpadTapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds momentum to a Touchpad swipe once a finger is lifted. Adds extra Mouse cursor travel than would be possible with the confined space on the Touchpad.
        /// </summary>
        public static string TouchpadTrackballEnableTooltip {
            get {
                return ResourceManager.GetString("TouchpadTrackballEnableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friction to virtual Trackball. Decreased friction will increase final mouse cursor travel time.
        /// </summary>
        public static string TouchpadTrackballFrictionTooltip {
            get {
                return ResourceManager.GetString("TouchpadTrackballFrictionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll.
        /// </summary>
        public static string TouchScroll {
            get {
                return ResourceManager.GetString("TouchScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        public static string TouchSlide {
            get {
                return ResourceManager.GetString("TouchSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        public static string TouchTap {
            get {
                return ResourceManager.GetString("TouchTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        public static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update .NET Runtime.
        /// </summary>
        public static string UpgradeNetCaption {
            get {
                return ResourceManager.GetString("UpgradeNetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please close DS4Windows and then run the PurgeOldXInput app from the Tools folder. A Windows reboot might be needed as well..
        /// </summary>
        public static string ViGEmPluginFailure {
            get {
                return ResourceManager.GetString("ViGEmPluginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Controller Settings.
        /// </summary>
        public static string VirtualControllerSettings {
            get {
                return ResourceManager.GetString("VirtualControllerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings only.
        /// </summary>
        public static string WarningsOnly {
            get {
                return ResourceManager.GetString("WarningsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XInputChecker.
        /// </summary>
        public static string XInputChecker {
            get {
                return ResourceManager.GetString("XInputChecker", resourceCulture);
            }
        }
    }
}
