//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS4Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS4Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_highlight {
            get {
                object obj = ResourceManager.GetObject("_360_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_map {
            get {
                object obj = ResourceManager.GetObject("_360_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _checked {
            get {
                object obj = ResourceManager.GetObject("_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A {
            get {
                object obj = ResourceManager.GetObject("A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of this action already exists.
        /// </summary>
        internal static string ActionExists {
            get {
                return ResourceManager.GetString("ActionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to list....
        /// </summary>
        internal static string AddingToList {
            get {
                return ResourceManager.GetString("AddingToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Programs.
        /// </summary>
        internal static string AddPrograms {
            get {
                return ResourceManager.GetString("AddPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A location must be picked to continue.
        /// </summary>
        internal static string ALocactionNeeded {
            get {
                return ResourceManager.GetString("ALocactionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Rainbow Mode.
        /// </summary>
        internal static string AlwaysRainbow {
            get {
                return ResourceManager.GetString("AlwaysRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to Controller *number*.
        /// </summary>
        internal static string AssignProfile {
            get {
                return ResourceManager.GetString("AssignProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B {
            get {
                object obj = ResourceManager.GetObject("B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BACK {
            get {
                object obj = ResourceManager.GetObject("BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery: *number*%.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best used with right side as a mouse function.
        /// </summary>
        internal static string BestUsedRightSide {
            get {
                return ResourceManager.GetString("BestUsedRightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BT {
            get {
                object obj = ResourceManager.GetObject("BT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move files to new location, Please rename the DS4Tool folder to &quot;DS4Windows&quot;.
        /// </summary>
        internal static string CannotMoveFiles {
            get {
                return ResourceManager.GetString("CannotMoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write at current location. Copy Settings to appdata?.
        /// </summary>
        internal static string CannotWriteHere {
            get {
                return ResourceManager.GetString("CannotWriteHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge the battery.
        /// </summary>
        internal static string ChargeController {
            get {
                return ResourceManager.GetString("ChargeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged.
        /// </summary>
        internal static string Charged {
            get {
                return ResourceManager.GetString("Charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging: *number*%.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Battery.
        /// </summary>
        internal static string CheckBattery {
            get {
                return ResourceManager.GetString("CheckBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close DS4Windows?.
        /// </summary>
        internal static string CloseDS4W {
            get {
                return ResourceManager.GetString("CloseDS4W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close DS4Windows via the notification icon.
        /// </summary>
        internal static string CloseMinimize {
            get {
                return ResourceManager.GetString("CloseMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color by Battey %.
        /// </summary>
        internal static string ColorByBattery {
            get {
                return ResourceManager.GetString("ColorByBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile for Controller *number*.
        /// </summary>
        internal static string ContextEdit {
            get {
                return ResourceManager.GetString("ContextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Profile for Controller *number*.
        /// </summary>
        internal static string ContextNew {
            get {
                return ResourceManager.GetString("ContextNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *Mac address* was removed or lost connection.
        /// </summary>
        internal static string ControllerWasRemoved {
            get {
                return ResourceManager.GetString("ControllerWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy complete, please relaunch DS4Windows and remove settings from Program Directory.
        /// </summary>
        internal static string CopyComplete {
            get {
                return ResourceManager.GetString("CopyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy the full color.
        /// </summary>
        internal static string CopyFullColor {
            get {
                return ResourceManager.GetString("CopyFullColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Could not open DS4 *Mac address* exclusively..
        /// </summary>
        internal static string CouldNotOpenDS4 {
            get {
                return ResourceManager.GetString("CouldNotOpenDS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile?.
        /// </summary>
        internal static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim by Battey %.
        /// </summary>
        internal static string DimByBattery {
            get {
                return ResourceManager.GetString("DimByBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off X360 input and only use the DS4&apos;s native input, hide ds4 must be off (Wired Only).
        /// </summary>
        internal static string DinputOnly {
            get {
                return ResourceManager.GetString("DinputOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect BT.
        /// </summary>
        internal static string DisconnectBT {
            get {
                return ResourceManager.GetString("DisconnectBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DOWN {
            get {
                object obj = ResourceManager.GetObject("DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading *number*%.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Version *number* now?.
        /// </summary>
        internal static string DownloadVersion {
            get {
                return ResourceManager.GetString("DownloadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string DownText {
            get {
                return ResourceManager.GetString("DownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DS4 {
            get {
                object obj = ResourceManager.GetObject("DS4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config {
            get {
                object obj = ResourceManager.GetObject("DS4_Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Circle {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Cross {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Down {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_L1 {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_L2 {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_L2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Left {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_LS {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_LS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Options {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_PS {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_PS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_R1 {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_R1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_R2 {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_R2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Right {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_RS {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_RS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Share {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Square {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_TouchLeft {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_TouchLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_TouchMulti {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_TouchMulti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_TouchRight {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_TouchRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_TouchUpper {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_TouchUpper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Triangle {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config_Up {
            get {
                object obj = ResourceManager.GetObject("DS4_Config_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Controller {
            get {
                object obj = ResourceManager.GetObject("DS4_Controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_lightbar {
            get {
                object obj = ResourceManager.GetObject("DS4_lightbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4Windows Update Available!.
        /// </summary>
        internal static string DS4Update {
            get {
                return ResourceManager.GetString("DS4Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DS4W {
            get {
                object obj = ResourceManager.GetObject("DS4W", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DS4W___White {
            get {
                object obj = ResourceManager.GetObject("DS4W___White", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4Windows cannot edit settings here, This will now close.
        /// </summary>
        internal static string DS4WindowsCannotEditHere {
            get {
                return ResourceManager.GetString("DS4WindowsCannotEditHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream EE {
            get {
                return ResourceManager.GetStream("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall Back.
        /// </summary>
        internal static string FallBack {
            get {
                return ResourceManager.GetString("FallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall Back to *button*.
        /// </summary>
        internal static string FallBackTo {
            get {
                return ResourceManager.GetString("FallBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th Mouse Button Down.
        /// </summary>
        internal static string FifthMouseDown {
            get {
                return ResourceManager.GetString("FifthMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th Mouse Button Up.
        /// </summary>
        internal static string FifthMouseUp {
            get {
                return ResourceManager.GetString("FifthMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change flash color. Black = default color.
        /// </summary>
        internal static string FlashAtTip {
            get {
                return ResourceManager.GetString("FlashAtTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush HID.
        /// </summary>
        internal static string FlushHID {
            get {
                return ResourceManager.GetString("FlushHID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush HID Queue after each reading.
        /// </summary>
        internal static string FlushHIDTip {
            get {
                return ResourceManager.GetString("FlushHIDTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Controller:.
        /// </summary>
        internal static string FoundController {
            get {
                return ResourceManager.GetString("FoundController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Mouse Button Down.
        /// </summary>
        internal static string FourthMouseDown {
            get {
                return ResourceManager.GetString("FourthMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Mouse Button Up.
        /// </summary>
        internal static string FourthMouseUp {
            get {
                return ResourceManager.GetString("FourthMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see readout of Sixaxis Gyro.
        /// </summary>
        internal static string GyroReadout {
            get {
                return ResourceManager.GetString("GyroReadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GyroX, Left and Right Tilt.
        /// </summary>
        internal static string GyroX {
            get {
                return ResourceManager.GetString("GyroX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GyroY, Forward and Back Tilt.
        /// </summary>
        internal static string GyroY {
            get {
                return ResourceManager.GetString("GyroY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GyroZ, Up and Down Tilt.
        /// </summary>
        internal static string GyroZ {
            get {
                return ResourceManager.GetString("GyroZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over items to see description or more about.
        /// </summary>
        internal static string HoverOverItems {
            get {
                return ResourceManager.GetString("HoverOverItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If removing DS4Windows, You can delete the settings following the profile folder link.
        /// </summary>
        internal static string IfRemovingDS4Windows {
            get {
                return ResourceManager.GetString("IfRemovingDS4Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Delay: *number*ms.
        /// </summary>
        internal static string InputDelay {
            get {
                return ResourceManager.GetString("InputDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Complete.
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Drivers here.
        /// </summary>
        internal static string InstallDriver {
            get {
                return ResourceManager.GetString("InstallDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Failed, Please Retry.
        /// </summary>
        internal static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Sixaxis to help calculate touchpad movement.
        /// </summary>
        internal static string Jitter {
            get {
                return ResourceManager.GetString("Jitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this window size after closing.
        /// </summary>
        internal static string KeepThisSize {
            get {
                return ResourceManager.GetString("KeepThisSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *number*&apos;s latency now under 10ms.
        /// </summary>
        internal static string LatencyNotOverTen {
            get {
                return ResourceManager.GetString("LatencyNotOverTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *number*&apos;s latency over 10ms.
        /// </summary>
        internal static string LatencyOverTen {
            get {
                return ResourceManager.GetString("LatencyOverTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch *program*.
        /// </summary>
        internal static string LaunchProgram {
            get {
                return ResourceManager.GetString("LaunchProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LB {
            get {
                object obj = ResourceManager.GetObject("LB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LEFT {
            get {
                object obj = ResourceManager.GetObject("LEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_touch {
            get {
                object obj = ResourceManager.GetObject("left_touch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also dim light by idle timeout if on.
        /// </summary>
        internal static string LightByBatteryTip {
            get {
                return ResourceManager.GetString("LightByBatteryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load *profile*.
        /// </summary>
        internal static string LoadProfile {
            get {
                return ResourceManager.GetString("LoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LS {
            get {
                object obj = ResourceManager.GetObject("LS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LSD {
            get {
                object obj = ResourceManager.GetObject("LSD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LSL {
            get {
                object obj = ResourceManager.GetObject("LSL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LSR {
            get {
                object obj = ResourceManager.GetObject("LSR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LSU {
            get {
                object obj = ResourceManager.GetObject("LSU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LT {
            get {
                object obj = ResourceManager.GetObject("LT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string Macro {
            get {
                return ResourceManager.GetString("Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro Recorded.
        /// </summary>
        internal static string MacroRecorded {
            get {
                return ResourceManager.GetString("MacroRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a New Profile.
        /// </summary>
        internal static string MakeNewProfile {
            get {
                return ResourceManager.GetString("MakeNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mouse {
            get {
                object obj = ResourceManager.GetObject("mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutli-Action Button.
        /// </summary>
        internal static string MultiAction {
            get {
                return ResourceManager.GetString("MultiAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newprofile {
            get {
                object obj = ResourceManager.GetObject("newprofile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No macro was recorded.
        /// </summary>
        internal static string NoMacroRecorded {
            get {
                return ResourceManager.GetString("NoMacroRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap none {
            get {
                object obj = ResourceManager.GetObject("none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string noneProfile {
            get {
                return ResourceManager.GetString("noneProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Profile Loaded.
        /// </summary>
        internal static string NoProfileLoaded {
            get {
                return ResourceManager.GetString("NoProfileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *number* is not using a profile.
        /// </summary>
        internal static string NotUsingProfile {
            get {
                return ResourceManager.GetString("NotUsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid.
        /// </summary>
        internal static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Installer.
        /// </summary>
        internal static string OpeningInstaller {
            get {
                return ResourceManager.GetString("OpeningInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Open ScpDriver.exe.
        /// </summary>
        internal static string OpenScpDriver {
            get {
                return ResourceManager.GetString("OpenScpDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , other location files will be deleted.
        /// </summary>
        internal static string OtherFileLocation {
            get {
                return ResourceManager.GetString("OtherFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pairmode {
            get {
                object obj = ResourceManager.GetObject("Pairmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Download the Updater now, and place it in the programs folder, then check for update again.
        /// </summary>
        internal static string PleaseDownloadUpdater {
            get {
                return ResourceManager.GetString("PleaseDownloadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please import or make a profile.
        /// </summary>
        internal static string PleaseImport {
            get {
                return ResourceManager.GetString("PleaseImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        internal static string PlusNewProfile {
            get {
                return ResourceManager.GetString("PlusNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Profile name* cannot be restored..
        /// </summary>
        internal static string ProfileCannotRestore {
            get {
                return ResourceManager.GetString("ProfileCannotRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Folder Moved to program folder.
        /// </summary>
        internal static string ProfileFolderMoved {
            get {
                return ResourceManager.GetString("ProfileFolderMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        internal static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERIMENTAL: Auto-Disable BT when conencting to USB.
        /// </summary>
        internal static string QuickCharge {
            get {
                return ResourceManager.GetString("QuickCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must quit other applications like Steam, Uplay before activating the &apos;Hide DS4 Controller&apos; option.&quot;.
        /// </summary>
        internal static string QuitOtherPrograms {
            get {
                return ResourceManager.GetString("QuitOtherPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rainbow {
            get {
                object obj = ResourceManager.GetObject("rainbow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rainbowC {
            get {
                object obj = ResourceManager.GetObject("rainbowC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RB {
            get {
                object obj = ResourceManager.GetObject("RB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string RecordText {
            get {
                return ResourceManager.GetString("RecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RIGHT {
            get {
                object obj = ResourceManager.GetObject("RIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_touch {
            get {
                object obj = ResourceManager.GetObject("right_touch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click to set presets for a set of controls.
        /// </summary>
        internal static string RightClickPresets {
            get {
                return ResourceManager.GetString("RightClickPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RS {
            get {
                object obj = ResourceManager.GetObject("RS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RSD {
            get {
                object obj = ResourceManager.GetObject("RSD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RSL {
            get {
                object obj = ResourceManager.GetObject("RSL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RSR {
            get {
                object obj = ResourceManager.GetObject("RSR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RSU {
            get {
                object obj = ResourceManager.GetObject("RSU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RT {
            get {
                object obj = ResourceManager.GetObject("RT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveprofile {
            get {
                object obj = ResourceManager.GetObject("saveprofile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Recorded Macro?.
        /// </summary>
        internal static string SaveRecordedMacro {
            get {
                return ResourceManager.GetString("SaveRecordedMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Code.
        /// </summary>
        internal static string ScanCode {
            get {
                return ResourceManager.GetString("ScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for controllers….
        /// </summary>
        internal static string SearchingController {
            get {
                return ResourceManager.GetString("SearchingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action for *action*.
        /// </summary>
        internal static string SelectActionTitle {
            get {
                return ResourceManager.GetString("SelectActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a macro.
        /// </summary>
        internal static string SelectMacro {
            get {
                return ResourceManager.GetString("SelectMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Regular Trigger.
        /// </summary>
        internal static string SetRegularTrigger {
            get {
                return ResourceManager.GetString("SetRegularTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Unload Trigger.
        /// </summary>
        internal static string SetUnloadTrigger {
            get {
                return ResourceManager.GetString("SetUnloadTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        internal static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for advanced Sixaxis reading.
        /// </summary>
        internal static string SixAxisReading {
            get {
                return ResourceManager.GetString("SixAxisReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap size {
            get {
                object obj = ResourceManager.GetObject("size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap START {
            get {
                object obj = ResourceManager.GetObject("START", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Install the DS4 Driver.
        /// </summary>
        internal static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Heavy.
        /// </summary>
        internal static string StopHText {
            get {
                return ResourceManager.GetString("StopHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Light.
        /// </summary>
        internal static string StopLText {
            get {
                return ResourceManager.GetString("StopLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped DS4Windows.
        /// </summary>
        internal static string StoppedDS4Windows {
            get {
                return ResourceManager.GetString("StoppedDS4Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping DS4 Controllers.
        /// </summary>
        internal static string StoppingDS4 {
            get {
                return ResourceManager.GetString("StoppingDS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping X360 Controllers.
        /// </summary>
        internal static string StoppingX360 {
            get {
                return ResourceManager.GetString("StoppingX360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Down.
        /// </summary>
        internal static string SwipeDown {
            get {
                return ResourceManager.GetString("SwipeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Left.
        /// </summary>
        internal static string SwipeLeft {
            get {
                return ResourceManager.GetString("SwipeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Right.
        /// </summary>
        internal static string SwipeRight {
            get {
                return ResourceManager.GetString("SwipeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Touchpad to change profiles.
        /// </summary>
        internal static string SwipeTouchpad {
            get {
                return ResourceManager.GetString("SwipeTouchpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Up.
        /// </summary>
        internal static string SwipeUp {
            get {
                return ResourceManager.GetString("SwipeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap and hold to drag, slight delay with single taps.
        /// </summary>
        internal static string TapAndHold {
            get {
                return ResourceManager.GetString("TapAndHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Heavy.
        /// </summary>
        internal static string TestHText {
            get {
                return ResourceManager.GetString("TestHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Light.
        /// </summary>
        internal static string TestLText {
            get {
                return ResourceManager.GetString("TestLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string TestText {
            get {
                return ResourceManager.GetString("TestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document (*.txt).
        /// </summary>
        internal static string TextDocs {
            get {
                return ResourceManager.GetString("TextDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Down.
        /// </summary>
        internal static string TiltDown {
            get {
                return ResourceManager.GetString("TiltDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Left.
        /// </summary>
        internal static string TiltLeft {
            get {
                return ResourceManager.GetString("TiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Right.
        /// </summary>
        internal static string TiltRight {
            get {
                return ResourceManager.GetString("TiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Up.
        /// </summary>
        internal static string TiltUp {
            get {
                return ResourceManager.GetString("TiltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad Movement is now Off.
        /// </summary>
        internal static string TouchpadMovementOff {
            get {
                return ResourceManager.GetString("TouchpadMovementOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad Movement is now On.
        /// </summary>
        internal static string TouchpadMovementOn {
            get {
                return ResourceManager.GetString("TouchpadMovementOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enable by pressing PS+Touchpad.
        /// </summary>
        internal static string TouchpadOffTip {
            get {
                return ResourceManager.GetString("TouchpadOffTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 finger touchpad swipe left or right.
        /// </summary>
        internal static string TwoFingerSwipe {
            get {
                return ResourceManager.GetString("TwoFingerSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type new name here.
        /// </summary>
        internal static string TypeNewName {
            get {
                return ResourceManager.GetString("TypeNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type profile name here.
        /// </summary>
        internal static string TypeProfileName {
            get {
                return ResourceManager.GetString("TypeProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        internal static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UP {
            get {
                object obj = ResourceManager.GetObject("UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string UpText {
            get {
                return ResourceManager.GetString("UpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are up to date.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap USB {
            get {
                object obj = ResourceManager.GetObject("USB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use your controller to change controls.
        /// </summary>
        internal static string UseControllerForMapping {
            get {
                return ResourceManager.GetString("UseControllerForMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Exclusive Mode.
        /// </summary>
        internal static string UsingExclusive {
            get {
                return ResourceManager.GetString("UsingExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *number* is using Profile “*Profile name*&quot;.
        /// </summary>
        internal static string UsingProfile {
            get {
                return ResourceManager.GetString("UsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Shared Mode.
        /// </summary>
        internal static string UsingShared {
            get {
                return ResourceManager.GetString("UsingShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disables the Touchpad as a mouse.
        /// </summary>
        internal static string UsingTPSwipes {
            get {
                return ResourceManager.GetString("UsingTPSwipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name.
        /// </summary>
        internal static string ValidName {
            get {
                return ResourceManager.GetString("ValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait *number*ms.
        /// </summary>
        internal static string WaitMS {
            get {
                return ResourceManager.GetString("WaitMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Keep.
        /// </summary>
        internal static string WillKeep {
            get {
                return ResourceManager.GetString("WillKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap X {
            get {
                object obj = ResourceManager.GetObject("X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use higher ports if you get conflicts in other emulating X360 programs, such as SCP&apos;s tool.
        /// </summary>
        internal static string XinputPorts {
            get {
                return ResourceManager.GetString("XinputPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml).
        /// </summary>
        internal static string XMLFiles {
            get {
                return ResourceManager.GetString("XMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Y {
            get {
                object obj = ResourceManager.GetObject("Y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
