//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS4WinWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS4WinWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of this action already exists.
        /// </summary>
        public static string ActionExists {
            get {
                return ResourceManager.GetString("ActionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to list....
        /// </summary>
        public static string AddingToList {
            get {
                return ResourceManager.GetString("AddingToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Programs.
        /// </summary>
        public static string AddPrograms {
            get {
                return ResourceManager.GetString("AddPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A location must be picked to continue.
        /// </summary>
        public static string ALocactionNeeded {
            get {
                return ResourceManager.GetString("ALocactionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Rainbow Mode.
        /// </summary>
        public static string AlwaysRainbow {
            get {
                return ResourceManager.GetString("AlwaysRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to Controller *number*.
        /// </summary>
        public static string AssignProfile {
            get {
                return ResourceManager.GetString("AssignProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^ABC = Match at the beginning of string (^) | ABC$ = Match at the end of string ($) | *ABC =Contains a string (*).
        /// </summary>
        public static string AutoProfilePathAndWindowTitleEditTip {
            get {
                return ResourceManager.GetString("AutoProfilePathAndWindowTitleEditTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery: *number*%.
        /// </summary>
        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best used with right side as a mouse function.
        /// </summary>
        public static string BestUsedRightSide {
            get {
                return ResourceManager.GetString("BestUsedRightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the poll rate used for the DS4 hardware when connected via Bluetooth. (Applies on profile save).
        /// </summary>
        public static string BTPollRate {
            get {
                return ResourceManager.GetString("BTPollRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move files to new location, Please rename the DS4Tool folder to &quot;DS4Windows&quot;.
        /// </summary>
        public static string CannotMoveFiles {
            get {
                return ResourceManager.GetString("CannotMoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write at current location. Copy Settings to appdata?.
        /// </summary>
        public static string CannotWriteHere {
            get {
                return ResourceManager.GetString("CannotWriteHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge the battery.
        /// </summary>
        public static string ChargeController {
            get {
                return ResourceManager.GetString("ChargeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged.
        /// </summary>
        public static string Charged {
            get {
                return ResourceManager.GetString("Charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging: *number*%.
        /// </summary>
        public static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Battery.
        /// </summary>
        public static string CheckBattery {
            get {
                return ResourceManager.GetString("CheckBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will disconnect all your connected controllers. Proceed?.
        /// </summary>
        public static string CloseConfirm {
            get {
                return ResourceManager.GetString("CloseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close DS4Windows?.
        /// </summary>
        public static string CloseDS4W {
            get {
                return ResourceManager.GetString("CloseDS4W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing main window minimizes app. Quitting app will be done via the notification icon.
        /// </summary>
        public static string CloseMinimize {
            get {
                return ResourceManager.GetString("CloseMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color by Battery %.
        /// </summary>
        public static string ColorByBattery {
            get {
                return ResourceManager.GetString("ColorByBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm....
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile for Controller *number*.
        /// </summary>
        public static string ContextEdit {
            get {
                return ResourceManager.GetString("ContextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Profile for Controller *number*.
        /// </summary>
        public static string ContextNew {
            get {
                return ResourceManager.GetString("ContextNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *Mac address* was removed or lost connection.
        /// </summary>
        public static string ControllerWasRemoved {
            get {
                return ResourceManager.GetString("ControllerWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy complete, please relaunch DS4Windows and remove settings from Program Directory.
        /// </summary>
        public static string CopyComplete {
            get {
                return ResourceManager.GetString("CopyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy the full color.
        /// </summary>
        public static string CopyFullColor {
            get {
                return ResourceManager.GetString("CopyFullColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Could not open DS4 *Mac address* exclusively..
        /// </summary>
        public static string CouldNotOpenDS4 {
            get {
                return ResourceManager.GetString("CouldNotOpenDS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile?.
        /// </summary>
        public static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim by Battery %.
        /// </summary>
        public static string DimByBattery {
            get {
                return ResourceManager.GetString("DimByBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect BT.
        /// </summary>
        public static string DisconnectBT {
            get {
                return ResourceManager.GetString("DisconnectBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading *number*%.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Version *number* now?.
        /// </summary>
        public static string DownloadVersion {
            get {
                return ResourceManager.GetString("DownloadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string DownText {
            get {
                return ResourceManager.GetString("DownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon DS4 {
            get {
                object obj = ResourceManager.GetObject("DS4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4Windows Update Available!.
        /// </summary>
        public static string DS4Update {
            get {
                return ResourceManager.GetString("DS4Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon DS4W {
            get {
                object obj = ResourceManager.GetObject("DS4W", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon DS4W___White {
            get {
                object obj = ResourceManager.GetObject("DS4W___White", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4Windows cannot edit settings here, This will now close.
        /// </summary>
        public static string DS4WindowsCannotEditHere {
            get {
                return ResourceManager.GetString("DS4WindowsCannotEditHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow touchpad mouse function to get toggled with PS + Touchpad Click..
        /// </summary>
        public static string EnableTouchToggle {
            get {
                return ResourceManager.GetString("EnableTouchToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall Back.
        /// </summary>
        public static string FallBack {
            get {
                return ResourceManager.GetString("FallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall Back to *button*.
        /// </summary>
        public static string FallBackTo {
            get {
                return ResourceManager.GetString("FallBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th Mouse Button Down.
        /// </summary>
        public static string FifthMouseDown {
            get {
                return ResourceManager.GetString("FifthMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th Mouse Button Up.
        /// </summary>
        public static string FifthMouseUp {
            get {
                return ResourceManager.GetString("FifthMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change flash color. Black = default color.
        /// </summary>
        public static string FlashAtTip {
            get {
                return ResourceManager.GetString("FlashAtTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush HID.
        /// </summary>
        public static string FlushHID {
            get {
                return ResourceManager.GetString("FlushHID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush HID Queue after each reading.
        /// </summary>
        public static string FlushHIDTip {
            get {
                return ResourceManager.GetString("FlushHIDTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Controller:.
        /// </summary>
        public static string FoundController {
            get {
                return ResourceManager.GetString("FoundController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Mouse Button Down.
        /// </summary>
        public static string FourthMouseDown {
            get {
                return ResourceManager.GetString("FourthMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Mouse Button Up.
        /// </summary>
        public static string FourthMouseUp {
            get {
                return ResourceManager.GetString("FourthMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see readout of Sixaxis Gyro.
        /// </summary>
        public static string GyroReadout {
            get {
                return ResourceManager.GetString("GyroReadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to have gyro active while trigger is active. Uncheck to disable gyro while trigger is active..
        /// </summary>
        public static string GyroTriggerBehavior {
            get {
                return ResourceManager.GetString("GyroTriggerBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GyroX, Left and Right Tilt.
        /// </summary>
        public static string GyroX {
            get {
                return ResourceManager.GetString("GyroX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GyroY, Forward and Back Tilt.
        /// </summary>
        public static string GyroY {
            get {
                return ResourceManager.GetString("GyroY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GyroZ, Up and Down Tilt.
        /// </summary>
        public static string GyroZ {
            get {
                return ResourceManager.GetString("GyroZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over items to see description or more about.
        /// </summary>
        public static string HoverOverItems {
            get {
                return ResourceManager.GetString("HoverOverItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If removing DS4Windows, You can delete the settings following the profile folder link.
        /// </summary>
        public static string IfRemovingDS4Windows {
            get {
                return ResourceManager.GetString("IfRemovingDS4Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Delay: {0:0.##} ms.
        /// </summary>
        public static string InputDelay {
            get {
                return ResourceManager.GetString("InputDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Complete.
        /// </summary>
        public static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Drivers here.
        /// </summary>
        public static string InstallDriver {
            get {
                return ResourceManager.GetString("InstallDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Failed, Please Retry.
        /// </summary>
        public static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Sixaxis to help calculate touchpad movement.
        /// </summary>
        public static string Jitter {
            get {
                return ResourceManager.GetString("Jitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this window size after closing.
        /// </summary>
        public static string KeepThisSize {
            get {
                return ResourceManager.GetString("KeepThisSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language pack change will take effect after DS4Windows application is restarted..
        /// </summary>
        public static string LanguagePackApplyRestartRequired {
            get {
                return ResourceManager.GetString("LanguagePackApplyRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller *number*&apos;s latency now under 10ms.
        /// </summary>
        public static string LatencyNotOverTen {
            get {
                return ResourceManager.GetString("LatencyNotOverTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0}&apos;s latency over 10ms ({1} ms).
        /// </summary>
        public static string LatencyOverTen {
            get {
                return ResourceManager.GetString("LatencyOverTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch *program*.
        /// </summary>
        public static string LaunchProgram {
            get {
                return ResourceManager.GetString("LaunchProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also dim light by idle timeout if enabled when DS4 is fully charged.
        /// </summary>
        public static string LightByBatteryTip {
            get {
                return ResourceManager.GetString("LightByBatteryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load *profile*.
        /// </summary>
        public static string LoadProfile {
            get {
                return ResourceManager.GetString("LoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        public static string Macro {
            get {
                return ResourceManager.GetString("Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the last key state when macro execution is completed (ie. if a key is left in down state then it is not automatically reset back to default state).
        /// </summary>
        public static string MacroKeepKeyStateTip {
            get {
                return ResourceManager.GetString("MacroKeepKeyStateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro Recorded.
        /// </summary>
        public static string MacroRecorded {
            get {
                return ResourceManager.GetString("MacroRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat a macro while the trigger key is held down.
        /// </summary>
        public static string MacroRepeatTip {
            get {
                return ResourceManager.GetString("MacroRepeatTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a macro on the trigger key release.
        /// </summary>
        public static string MacroRunOnReleaseTip {
            get {
                return ResourceManager.GetString("MacroRunOnReleaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a scan code value of keyboard keys in a macro.
        /// </summary>
        public static string MacroScanCodeTip {
            get {
                return ResourceManager.GetString("MacroScanCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run multiple macros in synchronized order if the same trigger has several macros (key down macro completed before key release macro is run).
        /// </summary>
        public static string MacroSynchronizedRunTip {
            get {
                return ResourceManager.GetString("MacroSynchronizedRunTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a New Profile.
        /// </summary>
        public static string MakeNewProfile {
            get {
                return ResourceManager.GetString("MakeNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutli-Action Button.
        /// </summary>
        public static string MultiAction {
            get {
                return ResourceManager.GetString("MultiAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No macro was recorded.
        /// </summary>
        public static string NoMacroRecorded {
            get {
                return ResourceManager.GetString("NoMacroRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string noneProfile {
            get {
                return ResourceManager.GetString("noneProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Profile Loaded.
        /// </summary>
        public static string NoProfileLoaded {
            get {
                return ResourceManager.GetString("NoProfileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} is not using a profile. Battery level is {1}%.
        /// </summary>
        public static string NotUsingProfile {
            get {
                return ResourceManager.GetString("NotUsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid.
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Installer.
        /// </summary>
        public static string OpeningInstaller {
            get {
                return ResourceManager.GetString("OpeningInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Open ScpDriver.exe.
        /// </summary>
        public static string OpenScpDriver {
            get {
                return ResourceManager.GetString("OpenScpDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable OSC Server. Listen to port on all addresses..
        /// </summary>
        public static string OscServer {
            get {
                return ResourceManager.GetString("OscServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , other location files will be deleted.
        /// </summary>
        public static string OtherFileLocation {
            get {
                return ResourceManager.GetString("OtherFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Download the Updater now, place it in the programs folder and rename to DS4Updater.exe if on x86, then check for update again. DS4Windows will attempt to open DS4Updater Release page when this window is closed..
        /// </summary>
        public static string PleaseDownloadUpdater {
            get {
                return ResourceManager.GetString("PleaseDownloadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please import or make a profile.
        /// </summary>
        public static string PleaseImport {
            get {
                return ResourceManager.GetString("PleaseImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        public static string PlusNewProfile {
            get {
                return ResourceManager.GetString("PlusNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Profile name* cannot be restored..
        /// </summary>
        public static string ProfileCannotRestore {
            get {
                return ResourceManager.GetString("ProfileCannotRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Folder Moved to program folder.
        /// </summary>
        public static string ProfileFolderMoved {
            get {
                return ResourceManager.GetString("ProfileFolderMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Disable BT when connecting to USB.
        /// </summary>
        public static string QuickCharge {
            get {
                return ResourceManager.GetString("QuickCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must quit other applications like UWP apps (Netflix), Steam, Uplay, Edge, NVIDIA IN-GAME before activating the &apos;Hide DS4 Controller&apos; option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues.
        /// </summary>
        public static string QuitOtherPrograms {
            get {
                return ResourceManager.GetString("QuitOtherPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string RecordText {
            get {
                return ResourceManager.GetString("RecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click to set presets for a set of controls.
        /// </summary>
        public static string RightClickPresets {
            get {
                return ResourceManager.GetString("RightClickPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tells Windows to start DS4Windows after login.
        /// </summary>
        public static string RunAtStartup {
            get {
                return ResourceManager.GetString("RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration of sixaxis wheel emulation.
        /// </summary>
        public static string SASteeringWheelEmulationCalibrate {
            get {
                return ResourceManager.GetString("SASteeringWheelEmulationCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All calibraton points are set when lightbar color turns to green. While turning the controller the lightbar color flashes when the controller is at calibration point. Accept calibration with OK button.
        /// </summary>
        public static string SASteeringWheelEmulationCalibrateInstruction {
            get {
                return ResourceManager.GetString("SASteeringWheelEmulationCalibrateInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) Center the controller, hold it steady and press &quot;X&quot;.
        /// </summary>
        public static string SASteeringWheelEmulationCalibrateInstruction1 {
            get {
                return ResourceManager.GetString("SASteeringWheelEmulationCalibrateInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2) Turn to 90Â° left (or right) position and press &quot;X&quot;.
        /// </summary>
        public static string SASteeringWheelEmulationCalibrateInstruction2 {
            get {
                return ResourceManager.GetString("SASteeringWheelEmulationCalibrateInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (3) Turn to 90Â° right (or left) position and press &quot;X&quot;.
        /// </summary>
        public static string SASteeringWheelEmulationCalibrateInstruction3 {
            get {
                return ResourceManager.GetString("SASteeringWheelEmulationCalibrateInstruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calibrate gyro (sixaxis) steering wheel emulation values without a controller. Connect a controller via bluetooth or usb.
        /// </summary>
        public static string SASteeringWheelEmulationCalibrateNoControllerError {
            get {
                return ResourceManager.GetString("SASteeringWheelEmulationCalibrateNoControllerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyro steering wheel emulation axis option is set to NONE (emulation is not used). Please select an axis option before calibrating the sixaxis gyro steering wheel emulation.
        /// </summary>
        public static string SASteeringWheelEmulationCalibrateNoneAxisError {
            get {
                return ResourceManager.GetString("SASteeringWheelEmulationCalibrateNoneAxisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Recorded Macro?.
        /// </summary>
        public static string SaveRecordedMacro {
            get {
                return ResourceManager.GetString("SaveRecordedMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Code.
        /// </summary>
        public static string ScanCode {
            get {
                return ResourceManager.GetString("ScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for controllers....
        /// </summary>
        public static string SearchingController {
            get {
                return ResourceManager.GetString("SearchingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action for *action*.
        /// </summary>
        public static string SelectActionTitle {
            get {
                return ResourceManager.GetString("SelectActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a macro.
        /// </summary>
        public static string SelectMacro {
            get {
                return ResourceManager.GetString("SelectMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Regular Trigger.
        /// </summary>
        public static string SetRegularTrigger {
            get {
                return ResourceManager.GetString("SetRegularTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Unload Trigger.
        /// </summary>
        public static string SetUnloadTrigger {
            get {
                return ResourceManager.GetString("SetUnloadTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled then Log tab page shows detailed messages of auto-profile events..
        /// </summary>
        public static string ShowAutoProfileDebugLogTip {
            get {
                return ResourceManager.GetString("ShowAutoProfileDebugLogTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for advanced Sixaxis reading.
        /// </summary>
        public static string SixAxisReading {
            get {
                return ResourceManager.GetString("SixAxisReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roundness of Square Stick corners.
        /// </summary>
        public static string SquareStickRoundness {
            get {
                return ResourceManager.GetString("SquareStickRoundness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Install the ViGEmBus Driver.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Heavy.
        /// </summary>
        public static string StopHText {
            get {
                return ResourceManager.GetString("StopHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Light.
        /// </summary>
        public static string StopLText {
            get {
                return ResourceManager.GetString("StopLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped DS4Windows.
        /// </summary>
        public static string StoppedDS4Windows {
            get {
                return ResourceManager.GetString("StoppedDS4Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping DS4 Input Controllers.
        /// </summary>
        public static string StoppingDS4 {
            get {
                return ResourceManager.GetString("StoppingDS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Virtual Output Controllers.
        /// </summary>
        public static string StoppingX360 {
            get {
                return ResourceManager.GetString("StoppingX360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Down.
        /// </summary>
        public static string SwipeDown {
            get {
                return ResourceManager.GetString("SwipeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Left.
        /// </summary>
        public static string SwipeLeft {
            get {
                return ResourceManager.GetString("SwipeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Right.
        /// </summary>
        public static string SwipeRight {
            get {
                return ResourceManager.GetString("SwipeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Touchpad to change profiles.
        /// </summary>
        public static string SwipeTouchpad {
            get {
                return ResourceManager.GetString("SwipeTouchpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Up.
        /// </summary>
        public static string SwipeUp {
            get {
                return ResourceManager.GetString("SwipeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap and hold to drag, slight delay with single taps.
        /// </summary>
        public static string TapAndHold {
            get {
                return ResourceManager.GetString("TapAndHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Heavy.
        /// </summary>
        public static string TestHText {
            get {
                return ResourceManager.GetString("TestHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Light.
        /// </summary>
        public static string TestLText {
            get {
                return ResourceManager.GetString("TestLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TestText {
            get {
                return ResourceManager.GetString("TestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document (*.txt).
        /// </summary>
        public static string TextDocs {
            get {
                return ResourceManager.GetString("TextDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Down.
        /// </summary>
        public static string TiltDown {
            get {
                return ResourceManager.GetString("TiltDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Left.
        /// </summary>
        public static string TiltLeft {
            get {
                return ResourceManager.GetString("TiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Right.
        /// </summary>
        public static string TiltRight {
            get {
                return ResourceManager.GetString("TiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Up.
        /// </summary>
        public static string TiltUp {
            get {
                return ResourceManager.GetString("TiltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad Movement is now Off.
        /// </summary>
        public static string TouchpadMovementOff {
            get {
                return ResourceManager.GetString("TouchpadMovementOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad Movement is now On.
        /// </summary>
        public static string TouchpadMovementOn {
            get {
                return ResourceManager.GetString("TouchpadMovementOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enable by pressing PS+Touchpad.
        /// </summary>
        public static string TouchpadOffTip {
            get {
                return ResourceManager.GetString("TouchpadOffTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 finger touchpad swipe left or right.
        /// </summary>
        public static string TwoFingerSwipe {
            get {
                return ResourceManager.GetString("TwoFingerSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type new name here.
        /// </summary>
        public static string TypeNewName {
            get {
                return ResourceManager.GetString("TypeNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type profile name here.
        /// </summary>
        public static string TypeProfileName {
            get {
                return ResourceManager.GetString("TypeProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to run DS4Windows as the Administrator in order to activate this mode..
        /// </summary>
        public static string UACTask {
            get {
                return ResourceManager.GetString("UACTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable UDP server. Server listen address and port. Address value options: 127.0.0.1 localhost only | 0.0.0.0 all addresses | Specific host name or IP address..
        /// </summary>
        public static string UdpServer {
            get {
                return ResourceManager.GetString("UdpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string UpText {
            get {
                return ResourceManager.GetString("UpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4Windows application is up-to-date..
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use your controller to change controls.
        /// </summary>
        public static string UseControllerForMapping {
            get {
                return ResourceManager.GetString("UseControllerForMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Exclusive Mode.
        /// </summary>
        public static string UsingExclusive {
            get {
                return ResourceManager.GetString("UsingExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} is using Profile &quot;{1}&quot;. Battery level is {2}%.
        /// </summary>
        public static string UsingProfile {
            get {
                return ResourceManager.GetString("UsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Shared Mode.
        /// </summary>
        public static string UsingShared {
            get {
                return ResourceManager.GetString("UsingShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disables the Touchpad as a mouse.
        /// </summary>
        public static string UsingTPSwipes {
            get {
                return ResourceManager.GetString("UsingTPSwipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name.
        /// </summary>
        public static string ValidName {
            get {
                return ResourceManager.GetString("ValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait *number*ms.
        /// </summary>
        public static string WaitMS {
            get {
                return ResourceManager.GetString("WaitMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Keep.
        /// </summary>
        public static string WillKeep {
            get {
                return ResourceManager.GetString("WillKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.xml file was corrupt. Starting from scratch..
        /// </summary>
        public static string XMLActionsCorrupt {
            get {
                return ResourceManager.GetString("XMLActionsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml).
        /// </summary>
        public static string XMLFiles {
            get {
                return ResourceManager.GetString("XMLFiles", resourceCulture);
            }
        }
    }
}
